### PR TITLE
add getUserId method

### PR DESCRIPTION
**Pull request by Alex123456780**
add `getUserId` method to get `userId` that you set with `setUserId` method.
This method returns `null` by default if you doesn't set `userId` with `setUserId` method.

### CODE REVIEW

**Comment by Alex123456780** [comment]
Need to fix README

**Comment by Alex123456780** [comment]
Now PR ready! 😄

**Comment by SudoPlz** [comment]
Looks good, thanks.. Published under 0.3.0

**Comment by Alex123456780** [comment]
Thanks @SudoPlz! Will we need to increment version in `package.json`? - i forgot to do it 😭

**Comment by SudoPlz** [comment]
Don't worry about it, I always increment before releasing. It's done.

**Comment by Alex123456780** [comment]
@SudoPlz sry for my inattention but we need to fix `README`:

`amplitude.getUserId();` <-- wrong way because we return `Promise`.

`amplitude.getUserId().then(userId => ...);` OR `await amplitude.getUserId()` <-- right way because we return `Promise<value>`.

**Comment by SudoPlz** [comment]
Feel free to create a new PR and I'll merge it.

**Pull request merged**
