### PR TITLE
Custom compileSdkVersion added

### PR DESCRIPTION
**Pull request by qvick1pro**
Updated to be able to set custom compileSdkVersion in rootProject

### CODE REVIEW

**Comment by SudoPlz** [comment]
Published in 0.2.4

**Comment by qvick1pro** [comment]
@SudoPlz Thanks!

**Comment by SudoPlz** [comment]
Thank you!

**Comment by qvick1pro** [comment]
@SudoPlz can you create 0.2.4 version tag?

**Pull request merged**
