### PR TITLE
add append & prepend methods with string-only values

### PR DESCRIPTION
**Pull request by Ryabchikus**
Hello
I partially implemented 'append' and 'prepend' methods of amplitude's SDK
"partially" means that methods work correctly only with strings arguments, 
Sorry for that, but maybe even such a bad implementation will be useful to someone.
I have no good background and/or experience in Objective С or Java then i have really big problems with types.

I hope, somebody more experienced changes my code for other supported by SDK data types

### CODE REVIEW

**Comment by SudoPlz** [comment]
Hey @Ryabchikus this looks good.
That's ok (the string only issue) but can you please make sure to add a javascript clause that makes sure the incoming value is a string, so that we at least catch the error on the JS side and not on the native side (somewhere before this line https://github.com/SudoPlz/react-native-amplitude-analytics/pull/65/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R198)?

**Comment by Ryabchikus** [comment]
@SudoPlz 
yea, you are right
i added a simple type check

**Comment by Ryabchikus** [comment]
@SudoPlz 
any news?

**Comment by SudoPlz** [comment]
@Ryabchikus apologies for the delay, I'm merging/releasing that now, it looks great.

**Comment by SudoPlz** [comment]
Released on 0.2.12

**Comment by Ryabchikus** [comment]
Great!
This is my first PR useful to anyone
Thank you for cool package!

**Comment by Ryabchikus** [comment]
I try to link here related Issue: SudoPlz/react-native-amplitude-analytics#42

**Comment by SudoPlz** [comment]
It's now available on 0.2.12

**Pull request merged**
