### PR TITLE
Use quoted import

### PR DESCRIPTION
**Pull request by lukem512**
When compiling I received an error complaining about the use of angular brackets. Substituting for a quoted import fixed the error and built successfully.

### CODE REVIEW

**Comment by SudoPlz** [comment]
I believe that has to do with wether you install amplitude via cocoapods or manually. In my case (both production project and the example project the bracket import works)

**Comment by lukem512** [comment]
Hmm, that's interesting. I installed using cocoapods with the latest version of XCode and it complained

**Comment by SudoPlz** [comment]
So in the latest version (0.1.6) a .podspec file was added. Could you try using `pod install` and let me know if you still experience problems? I'd be grateful.

**Comment by lukem512** [comment]
Using a fresh install of 0.1.6 still leads to the following error:

```
In file included from /Users/luke/Projects/proj/node_modules/react-native-amplitude-analytics/ios/AmplitudeSDK.m:1:
/Users/luke/Projects/proj/node_modules/react-native-amplitude-analytics/ios/AmplitudeSDK.h:2:9: fatal error: 'Amplitude/Amplitude.h' file not found
#import <Amplitude/Amplitude.h>
        ^
1 error generated.
```

**Comment by lukem512** [comment]
So, the issue above is caused by the react-native project being in a subdirectory of the project root (such as `/react-native/`). This is a separate issue caused by the path hardcoded [here](https://github.com/SudoPlz/react-native-amplitude-analytics/blob/master/ios/RNAmplitudeSDK.xcodeproj/project.pbxproj#L203) and [here](https://github.com/SudoPlz/react-native-amplitude-analytics/blob/master/ios/RNAmplitudeSDK.xcodeproj/project.pbxproj#L225).

**Comment by SudoPlz** [comment]
Hi @lukem512 , thank you so much for digging into this.
Would you mind explaining a bit further?
Define the `react-native` project term please, do you mean:

- The react-native project of the person using this library?
- The react-native example project of this library?
- The javascript part of this library?

Thanks.

**Comment by lukem512** [comment]
You're welcome - I'm hoping to use this module and so it's part of the work I'm doing also.

My directory tree is as follows:

`/` - project root
`package.json` - shared dependencies for all subprojects
`/node_modules/*` - node modules for all subprojects
`/web/` - web client (react project)
`/native/` - native client (react-native project)
`/native/ios/Project.xcodeproj` - xCode project for native client

**Comment by SudoPlz** [comment]
Got it, hmm, so I guess you'd need another head path there: `$(SRCROOT)/../../../native/ios/Pods/Amplitude-iOS`.

Not sure how I can dynamically set header paths depending on the actual location of the react-native ios project of the user. (`/native/ios/Project.xcodeproj`)

**Comment by lukem512** [comment]
That's what I was wondering, if there was a solution to that problem. I think I'll close this as it's wandered onto another issue - the existing problem seems to be no longer an issue.

**Comment by SudoPlz** [comment]
Ok, sure. You can use your own forked repo for the time being and update it from time to time. If you think of a solution feel free to let me know.

**Pull request closed without merging**
